services:
  mysql:
    image: mysql:8.0
    restart: on-failure
    environment:
      MYSQL_ALLOW_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: sym64michael
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
  nginx:
      image: nginx:latest
      ports:
        - "8080:80"
      volumes:
        - './public/:usr/src/app'
        - './docker/nginx:/etc/nginx/conf.d/'
      depends_on:
        - php
#  adminer:
#      image: adminer
#      restart: always
#      ports:
#        - '8081:8080'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    ports:
      - "8081:80"


  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - './public/:/usr/src/app'
    restart: on-failure
    env_file:
      - .env

volumes:
  mysql_data:
networks:
  app-network:
